### PR TITLE
Identify missing data

### PR DESCRIPTION
**Pull request by kiadso**
Hi-
This is in response to Issue rlgbtq/TDoR2018#2.

In the identify-missing-data script, I created data frames to use for displaying missing data in the tdor file. In the comments are suggestions as to how to describe what data the user would be seeing.

proposed-data-corrections: In examining the tdor file, I came across a couple of Names where it looks like "Name Unknown" was inside the Name value so I wrote code that checks for instances where that is true.

Also noticed that Location seems to be missing for some records even though the Lat/Long is there. I imported some data with those missing place names so that we could perhaps populate the Location variable with the more granular (than Country) data. Alternatively, the Location variable could be replaced with the Country variable. I would have joined the calculated Location data back to tdor, but the values that contained non ASCII characters were being NA'd and I'm not even sure this is something that's useful since it's only tangentially related to the Issue. If this is something that is needed, please let me know and I will try to figure out how to get all the values into the tdor file.

This is my first time to contribute to a project outside my own work, and I'd be really interested to hear any feedback regarding my code or any relevant information I may need to know. Thanks!

### CODE REVIEW

**Comment by annajayne** [comment]
"Name Unknown" pops up a lot, as many murder victims in Latin America are found without identifying documents.

In some cases the Location field (which you can think of as "all of the location bits except the country) is empty as we only know the country. In such cases the Lat/Long value given is usually the centre of the country, so it's *very* approximate.

I'm open to splitting Location apart into its constituent parts but it would take a while as it would mean checking all existing data and updating the website code to match.

Finally, all of the CSV files are UTF-8 encoded so you'll need to bear that in mind while parsing them. Non-ASCII characters are found in many Name, Location and Description fields.

**Comment by kiadso** [comment]
I hear you about the Location. I think splitting City and State out would be nice too, in which case it would make sense to leave them as null since it's not known.

As far as Name Unknown, maybe I wasn't clear. The code I submitted finds the two rows I'm talking about where the name is like "MarName Unknowny Collins".

**Comment by annajayne** [comment]
Ah got it! If you can identify the entries in question I'll check them - I'm pretty sure that's fixed already in Bitbucket so if you update your data set they should disappear.

**Comment by kiadso** [comment]
Ok, I'll work on this this week. I'm also going to add some functionality so that the code generates a csv or markdown. What would be better for the project? I need to learn markdown, so this could be a good way.

I'll also remove the code (and data) regarding Location.

Thanks!

**Comment by kiadso** [comment]
Ok, I'll work on this this week. I'm also going to add some functionality so that the code generates a csv or markdown. What would be better for the project? I need to learn markdown, so this could be a good way.

I'll also remove the code (and data) regarding Location.

Thanks!

**Comment by annajayne** [comment]
CSV works best as an output format when the output CSV has the same fields as the input and Markdown when a human has to read it or the result will be committed to DVCS.

If you're trying to decide an output format, I'd structure it so the output bit is logically separated from the bit that decides what data needs fixing, then you can add new output formats as required.

FYI in the data itself the only field which should use (basic) markdown in the CSV is the Description, and even then it only supports a couple of tags (> and -) at the moment (I need to add bold, italic, embedded video etc. but that's for another day). Other fields are plaintext, but all are UTF-8.

**Comment by kiadso** [comment]
Hi Anna-

Sorry, I'm really new at this and I think I may have forked the incorrect
repository.. I am working on an Issue on the rlgbtq/TDoR2018 but I actually
forked and pull requested to CaRdiffR/tdor. So I guess I could use some
clarification about what the relationship is between the two repositories..
There's now a dashboard on the rlgbtq one, which I think would be a good
place for me to add some of the code I've written organizing the collection
of missing data, but I already pull requested to your repository so I am
just not sure if that was the right idea or if I should unpull request the
CaRdiffR repository and fork the rlgbtq one and work within that one.

Let me know how I might be of help in sorting this out.

Thanks for your patience!
Genelle

**Pull request closed without merging**
